### PR TITLE
Stop Button

### PR DESCRIPTION
**Pull request by gmelsby**
Added a Stop button that appears under the responseDiv when a request is being processed. Goes away after all text is generated or request is cancelled. 

This appears to halt the execution of processing on the server as well. If you ask llama to tell you a long story and hit 'Stop' when text starts appearing, the ollama process appears to halt generation, so you don't have to wait for the entire run to complete. 
I had to make some changes to the way spinner is implemented so that it unmounts when the user hits 'Stop' when no text has been generated and added to the responseDiv yet.

### CODE REVIEW

**Comment by rtcfirefly** [comment]
It might just be on my machine, but I get a segfault when I hit stop (which kills the server)

```
llama_print_timings:        load time =  5005.36 ms
llama_print_timings:      sample time =     2.71 ms /    18 runs   (    0.15 ms per token,  6651.88 tokens per second)
llama_print_timings: prompt eval time =  4627.68 ms /   148 tokens (   31.27 ms per token,    31.98 tokens per second)
llama_print_timings:        eval time =   979.50 ms /    17 runs   (   57.62 ms per token,    17.36 tokens per second)
llama_print_timings:       total time =  5632.17 ms
ggml_metal_free: deallocating
zsh: segmentation fault  ollama serve
```

**Comment by gmelsby** [comment]
It's not just your machine! I've been using with the [manual build](https://github.com/jmorganca/ollama#building) and it's worked fine, but I installed the apple silicon pre-built application to test compatibility and am also getting the segfault.

**Comment by rtcfirefly** [comment]
Looks like `v0.0.13` doesn't crash. Feel free to reopen if you like

**Comment by gmelsby** [comment]
Thanks for figuring that out!! I was half-convinced that it had something to do with the fact that the installable version seemed to be using metal while my manual build version wasn't. Glad you saved me from going down that rabbit hole.

**Review by rtcfirefly — APPROVED** [review]

**Pull request merged**
